### ISSUE TITLE
Failed container start in cron 'upgrade-blimp.sh'

### ISSUE THREAD

**Issue by easye** [cloudfleet/blimp-engineroom#5]
Unfortunately my RPi2 based blimp failed that 'upgrade-blimp.sh' this morning.

The nginx container failed to start even after the generous number of retries.

[container-startup-failure-20151220a.txt](https://github.com/cloudfleet/blimp-engineroom/files/67786

Either we need to move the containers off the encrypted storage, or we need to find and fix the underlying cause.

**Comment by metakermit** [comment]
`docker logs blimp_cockpit_1` will have an error related to user/privileges of the nginx user if it's the thing I caused yesterday (which should be resolved by now).

> BTW, don't get surprised if your blimp is erroring out when you try to access it, try ./blimp-upgrade.sh or wait for 24 h, because I think I left an image of blimp-cockpit with an error yesterday on marina. The version that's up there now works again, so your blimps should pick up on it on their own during the nightly update.

**Comment by easye** [comment]
@metakermit:  Thanks for the update.  Re-running `upgrade-blimp.sh` to verify that it works.

**Comment by easye** [comment]
`upgrade-blimp.sh` completed successfully.

```
2015-12-20 14:41:50 Upgrade and restart took 869 seconds
```

@metakermit Close this issue at your discretion.  From the way I read the logs for this issue, I encountered timeouts on the container start rather than a problem to start the cockpit.

**Comment by metakermit** [comment]
I'll close it for now. If you experience it again, reopen and paste the actual error messages in here (I couldn't find the offending lines in the large file you attached) and the `docker logs` output of the container that was failing to start. For now I'm suspecting that this commit https://github.com/cloudfleet/blimp-cockpit/commit/24ad1892dd5d814e2d43778afd6833379334c771 fixed it, because before it, blimp-cockpit was failing, which wasn't allowing blimp-nginx to start either (as it requires the cockpit host to exist).

**Comment by easye** [comment]
The relevant part of the logs (as far as I can determine):

```
  2015-12-20 04:43:32 Starting containers ... 
  ==============================
  The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
  Creating blimp_conduit_1
  Creating blimp_doveshed_1
  Creating blimp_mailpileeasye_1
  Creating blimp_musterroll_1
  Creating blimp_radicale_1
  Creating blimp_mailbox_1
  Creating blimp_cockpit_1
  Creating blimp_wellknown_1
  Creating blimp_nginx_1
  Creating blimp_pagekite_1
  retry
  The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
  blimp_conduit_1 is up-to-date
  blimp_doveshed_1 is up-to-date
  blimp_mailpileeasye_1 is up-to-date
  blimp_musterroll_1 is up-to-date
  blimp_radicale_1 is up-to-date
  blimp_mailbox_1 is up-to-date
  Starting blimp_cockpit_1
  blimp_wellknown_1 is up-to-date
  Starting blimp_nginx_1
  blimp_pagekite_1 is up-to-date
  retry
  The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
  blimp_conduit_1 is up-to-date
  blimp_doveshed_1 is up-to-date
  blimp_mailpileeasye_1 is up-to-date
  blimp_musterroll_1 is up-to-date
  blimp_radicale_1 is up-to-date
  blimp_mailbox_1 is up-to-date
  Starting blimp_cockpit_1
  blimp_wellknown_1 is up-to-date
  Starting blimp_nginx_1
  blimp_pagekite_1 is up-to-date
  stopping after 3 tries
```

which is clear as mud what actually failed…

**Comment by metakermit** [comment]
I don't see any errors here. Aside from the variable rename deprecation, this is just my retry logic that is triggered if 10 containers are not up after docket-compose up is called. Since it stopped after 3 tries (which is less than the max of 20), it managed to get 10 up at the same time.

Unless you can give me the logs of the container that failed, there is nothing else I can do with this log output.

**Comment by easye** [comment]
Thanks for checking.  Closing.

**Comment by easye** [comment]
re-opening.

My containers failed to start correctly after last night's (2015-12-21) upgrade.  

I receive a "502 Bad Gateway" from nginx on viewing my Blimp's main URI , which is different from my previously reported problem.  But the `start-containers.sh` script is still the culprit: 

```
015-12-21 04:31:14 Starting containers ...
==============================
The DOCKER_CLIENT_TIMEOUT environment variable is deprecated. Please use COMPOSE_HTTP_TIMEOUT instead.
Creating blimp_conduit_1
Creating blimp_doveshed_1
Creating blimp_mailpileeasye_1
Creating blimp_musterroll_1
Creating blimp_radicale_1
Creating blimp_mailbox_1
Creating blimp_cockpit_1
Creating blimp_wellknown_1
Creating blimp_nginx_1
Creating blimp_pagekite_1
stopping after 1 tries
```

A `docker ps -a`

```
ONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS              PORTS               NAMES
e7aa8582d3e1        registry.marina.io/cloudfleet/blimp-pagekite     "/bin/sh -c 'pagekite"   4 hours ago         Up 4 hours                              blimp_pagekite_1
12b27ba164e8        registry.marina.io/cloudfleet/blimp-nginx        "/bin/sh -c /root/sta"   4 hours ago         Up 4 hours          80/tcp, 443/tcp     blimp_nginx_1
14a0e58d665e        registry.marina.io/cloudfleet/blimp-wellknown    "/bin/sh -c 'python -"   4 hours ago         Up 4 hours          80/tcp              blimp_wellknown_1
981c8e2660a0        registry.marina.io/cloudfleet/blimp-cockpit      "nginx -g 'daemon off"   4 hours ago         Up 4 hours          80/tcp, 443/tcp     blimp_cockpit_1
c5b51f50ac1e        registry.marina.io/cloudfleet/blimp-mailbox      "/bin/sh -c 'python /"   4 hours ago         Up 4 hours          3000/tcp            blimp_mailbox_1
0d5c21bdbe60        registry.marina.io/cloudfleet/blimp-radicale     "/bin/sh -c scripts/s"   4 hours ago         Up 4 hours          80/tcp              blimp_radicale_1
64a50d8b6ce1        registry.marina.io/cloudfleet/blimp-musterroll   "npm start"              4 hours ago         Up 4 hours          80/tcp, 389/tcp     blimp_musterroll_1
07e3829c3237        registry.marina.io/cloudfleet/blimp-mailpile     "/bin/sh -c /opt/clou"   4 hours ago         Up 4 hours          33411/tcp           blimp_mailpileeasye_1
16db9d8dcd06        registry.marina.io/cloudfleet/blimp-doveshed     "/bin/sh -c ./start.s"   4 hours ago         Up 4 hours          25/tcp              blimp_doveshed_1
c102f501239d        registry.marina.io/cloudfleet/blimp-conduit      "/bin/sh -c '/usr/bin"   4 hours ago         Up 4 hours          5000/tcp            blimp_conduit_1
```

Short term strategy towards fixing:  more debugging information from the `start-containers.sh` script as to what is going on.

**Comment by easye** [comment]
Closing as not replicated.
